import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final primaryColorProvider = Provider<Color>((ref) => const Color(0xFFFFFFFF));
final blueColorProvider = Provider<Color>((ref) => const Color(0xFF0E82FD));
final greyColorProvider = Provider<Color>((ref) => const Color(0xFF6B6C70));
final lightGreyColorProvider = Provider<Color>((ref) => const Color(0xFFADB3BC));
final blackColorProvider = Provider<Color>((ref) => const Color(0xFF000000));
final containerOneColorProvider = Provider<Color>((ref) => const Color(0xFFF3F2E9));
final containerTwoColorProvider = Provider<Color>((ref) => const Color(0xFFE4E9EE));
final containerThreeColorProvider = Provider<Color>((ref) => const Color(0xFFF6F9FE));
final lightBlueColorProvider = Provider<Color>((ref) => const Color(0xFFD9E4FF));
final greenColorProvider = Provider<Color>((ref) => const Color(0xFF22C55E));
final yellowColorProvider = Provider<Color>((ref) => const Color(0xFFFFD600));
final lightYellowColorProvider = Provider<Color>((ref) => const Color(0xFFFEF6EC));
final redColorProvider = Provider<Color>((ref) => const Color(0xFFFF4C5E));
final lightRedColorProvider = Provider<Color>((ref) => const Color(0xFFFDF1F3));
final unClickedButtonColorProvider = Provider<Color>((ref) => const Color(0xFFF2F4F7));
final orangeColorProvider = Provider<Color>((ref) => const Color(0xFFE8753D));
final purpleColorProvider = Provider<Color>((ref) => const Color(0xFFDCDBFF));
